version: '3'
services:
  c-nginx-load-balancer:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/
      - ./../log/:/var/log/nginx/
      - ./../../html/:/usr/share/nginx/html/
    restart: always
    networks:
      - nginx-load-balancer
networks:
  nginx-load-balancer:
