version: '3'
services:
  c-nginx-load-balancer:
    image: nginx:1.15.8-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./../log/:/var/log/nginx/
      - ./../../html/:/usr/share/nginx/html/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./dhparams.pem:/etc/ssl/private/dhparams.pem
    restart: always
    networks:
      - nginx-load-balancer
networks:
  nginx-load-balancer:
